import os
import matplotlib

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import numpy as np

_CJK_FONT_PATH = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"
_CJK_FONT = fm.FontProperties(fname=_CJK_FONT_PATH)
matplotlib.rcParams['axes.unicode_minus'] = False  


def plot_monitoring(csv_path, save_path=None):
    """
    Plot resource monitoring data from CSV file generated by ResourceMonitor.

    Parameters
    ----------
    csv_path : str
        Path to the CSV file (e.g. 'video1.csv').
        Expected columns: elapsed_s, workload, CPU_Util_Pct, GPU_Mem_Pct,
                         GPU_Temp_C, GPU_Util_Pct, RAM_Util_Pct
    save_path : str or None
        Picture save path, if None, just show the plot without saving.
    """
    df = pd.read_csv(csv_path)

    # Check required columns
    if 'elapsed_s' not in df.columns or 'workload' not in df.columns:
        raise ValueError("CSV must contain 'elapsed_s' and 'workload' columns")

    # Identify metric columns (exclude elapsed_s and workload)
    metric_cols = [c for c in df.columns if c not in ('elapsed_s', 'workload')]
    if not metric_cols:
        raise ValueError("No metric columns found in CSV")

    # Map to standard names for plotting
    time_col = 'elapsed_s'
    func_col = 'workload'

    # Fill NaN workload with empty string
    df[func_col] = df[func_col].fillna('')

    # Identify function blocks based on changes in the workload column
    df['Block'] = (df[func_col] != df[func_col].shift()).cumsum()
    blocks = df.groupby('Block').agg(
        Start=(time_col, 'first'),
        End=(time_col, 'last'),
        Function=(func_col, 'first')
    ).reset_index(drop=True)
    # Filter out empty workload blocks
    blocks = blocks[blocks['Function'] != ''].reset_index(drop=True)

    # Assign colors for each block
    if len(blocks) > 0:
        colors = plt.cm.tab10(np.linspace(0, 1, len(blocks)))
    else:
        colors = []

    # Plotting
    n_metrics = len(metric_cols)
    fig, axes = plt.subplots(n_metrics, 1, sharex=True, figsize=(14, 2 * n_metrics + 2))
    if n_metrics == 1:
        axes = [axes]

    for ax, col in zip(axes, metric_cols):
        ax.plot(df[time_col], df[col], color='black', linewidth=0.8)
        ax.set_ylabel(col)
        ax.grid(True, linestyle='--', alpha=0.5)

        # Highlight function blocks
        for i, row in blocks.iterrows():
            start, end, func = row['Start'], row['End'], row['Function']
            ax.axvspan(start, end, alpha=0.15, color=colors[i],
                       label=func if ax == axes[0] else "")
            mid = start + (end - start) / 2
            ylim = ax.get_ylim()
            ax.text(mid, ylim[1] * 0.92, func, ha='center', va='top',
                    fontsize=8, fontproperties=_CJK_FONT,
                    bbox=dict(boxstyle='round,pad=0.2',
                    facecolor=colors[i], alpha=0.5))

    axes[-1].set_xlabel('Elapsed Time (seconds)')

    # Create legend for function blocks (only in the first subplot)
    if len(blocks) > 0:
        legend_handles = [plt.Rectangle((0, 0), 1, 1, facecolor=colors[i], alpha=0.15)
                          for i in range(len(blocks))]
        axes[0].legend(legend_handles, blocks['Function'].tolist(),
                       loc='upper right', fontsize=7, ncol=2,
                       prop=_CJK_FONT)

    plt.tight_layout()
    if save_path:
        if os.path.isfile(save_path):
            os.remove(save_path)
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close() 